name: Exécuter le script Playwright

on: [push]

jobs:
  fetch-data:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y libgtk-4-dev libgraphene-1.0-dev libwoff2 libvpx-dev libevent-dev libopus-dev \
                                libgstallocators-1.0-dev libgstapp-1.0-dev libgstpbutils-1.0-dev libgstaudio-1.0-dev \
                                libgstgl-1.0-dev libgsttag-1.0-dev libgstvideo-1.0-dev libgstcodecparsers-1.0-dev \
                                libgstfft-1.0-dev libflite-dev libavif-dev libharfbuzz-icu-dev libsecret-1-dev libhyphen-dev \
                                libmanette-0.2-dev libgles2-mesa-dev libx264-dev
        pip install playwright

    - name: Run fetch_data.py
      run: python .github/workflows/fetch_data.py
