name: Récupérer JSON avec Puppeteer

on:
  schedule:
    - cron: '0 * * * *'  # Exécute toutes les heures
  workflow_dispatch:

jobs:
  fetch-json:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Installer Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'  # Updated to Node.js 18
      - name: Installer les dépendances
        run: npm install puppeteer
      - name: Exécuter le script
        run: node fetchData.js
      - name: Afficher le contenu JSON
        run: cat data.json
