name: Exécuter le script Playwright

# Le workflow s'exécutera à chaque push sur la branche principale et peut être déclenché manuellement.
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  run-playwright:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout du code
        uses: actions/checkout@v3

      - name: Configuration de Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Installer les dépendances
        run: |
          python -m pip install --upgrade pip
          pip install playwright
          # Installer les navigateurs pour Playwright (à faire une seule fois)
          playwright install

      - name: Exécuter le script
        run: python fetch_data.py
