name: Run Python Script and Commit JSON

on:
  workflow_dispatch:
  schedule:
    - cron: '0 7 * * *'   # Exécuter à 08h00 heure locale (07h00 UTC)
    - cron: '0 11 * * *'  # Exécuter à 12h00 heure locale (11h00 UTC)

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Nécessaire pour pouvoir commiter des changements dans l'historique complet

      - name: Cache pip packages
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.9

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          sudo apt-get update
          sudo apt-get install -y chromium-chromedriver
          export PATH=$PATH:/usr/lib/chromium-browser/

      - name: Run Python script
        run: python .github/workflows/script.py

      - name: Commit pegsu.json to repository
        uses: EndBug/add-and-commit@v9
        with:
          message: "Update pegsu.json"
          add: ".github/workflows/pegsu.json"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
