name: Exécuter le script Playwright

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  run-playwright:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout du code
        uses: actions/checkout@v3

      - name: Configuration de Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Installer les dépendances
        run: |
          python -m pip install --upgrade pip
          pip install playwright
          playwright install

      - name: Exécuter le script fetch_data.py
        run: python .github/workflows/fetch_data.py
