name: Exécuter le script Selenium

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  run-selenium:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout du code
        uses: actions/checkout@v3

      - name: Configuration de Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Installer les dépendances
        run: |
          python -m pip install --upgrade pip
          pip install selenium selenium-wire
          # Installer Chromium et Chromedriver (disponible sur ubuntu-latest)
          sudo apt-get update
          sudo apt-get install -y chromium-chromedriver
          # Parfois, il faut ajouter le chemin du chromedriver dans PATH :
          export PATH=$PATH:/usr/lib/chromium-browser/

      - name: Exécuter le script Selenium
        # Si votre script se trouve à la racine et s'appelle "script.py"
        run: python script.py
